# -*- coding: utf-8 -*-
"""task1-iremyuvali.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yzCb9G1Etp8H_D0e1Gc-9S_Flk39FPuy

**irem yuvali | 2017555071**
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.neighbors import KNeighborsClassifier
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

iris = load_iris()
iris.data

iris_data=pd.DataFrame(iris.data)
iris_data

iris_data.describe()

x, y = iris.data, iris.target

plt.scatter(x[:,0],x[:,1])
plt.title("the iris data")
plt.show()

y

plt.scatter(x[:,0],x[:,1],c=y)
plt.title("the target data")
plt.show()

km_model = KMeans(n_clusters=3)
km = km_model.fit(iris_data)

km.labels_

plt.scatter(x[:,0],x[:,1],c=km.labels_)
plt.title("k-means k=3")
plt.show()

acc_km = accuracy_score(y, km.labels_ )
print(acc_km)

x_train, x_test, y_train, y_test = train_test_split(x,y, random_state=50)

knn_model = KNeighborsClassifier(n_neighbors=3)
knn = knn_model.fit(x_train, y_train)

knn_labels = knn_model.predict(x)
knn_labels

plt.scatter(x[:,0],x[:,1], c=knn_labels)
plt.title("k-nearest neighbors n=3")
plt.show()

y_pred = knn_model.predict(x_test)
acc_knn = accuracy_score(y_test, y_pred)
print(acc_knn)